// Canonical logical asset manifest. Keep entries as an array so verification can detect duplicate keys.
export const ASSET_ENTRIES = Object.freeze([
  Object.freeze({ key: 'raider.n.idle', url: '/assets/raider_n_idle.png' }),
  Object.freeze({ key: 'raider.n.run1', url: '/assets/raider_n_run1.png' }),
  Object.freeze({ key: 'raider.n.run2', url: '/assets/raider_n_run2.png' }),
  Object.freeze({ key: 'raider.ne.idle', url: '/assets/raider_ne_idle.png' }),
  Object.freeze({ key: 'raider.ne.run1', url: '/assets/raider_ne_run1.png' }),
  Object.freeze({ key: 'raider.ne.run2', url: '/assets/raider_ne_run2.png' }),
  Object.freeze({ key: 'raider.e.idle', url: '/assets/raider_e_idle.png' }),
  Object.freeze({ key: 'raider.e.run1', url: '/assets/raider_e_run1.png' }),
  Object.freeze({ key: 'raider.e.run2', url: '/assets/raider_e_run2.png' }),
  Object.freeze({ key: 'raider.se.idle', url: '/assets/raider_se_idle.png' }),
  Object.freeze({ key: 'raider.se.run1', url: '/assets/raider_se_run1.png' }),
  Object.freeze({ key: 'raider.se.run2', url: '/assets/raider_se_run2.png' }),
  Object.freeze({ key: 'raider.s.idle', url: '/assets/raider_s_idle.png' }),
  Object.freeze({ key: 'raider.s.run1', url: '/assets/raider_s_run1.png' }),
  Object.freeze({ key: 'raider.s.run2', url: '/assets/raider_s_run2.png' }),
  Object.freeze({ key: 'raider.sw.idle', url: '/assets/raider_sw_idle.png' }),
  Object.freeze({ key: 'raider.sw.run1', url: '/assets/raider_sw_run1.png' }),
  Object.freeze({ key: 'raider.sw.run2', url: '/assets/raider_sw_run2.png' }),
  Object.freeze({ key: 'raider.w.idle', url: '/assets/raider_w_idle.png' }),
  Object.freeze({ key: 'raider.w.run1', url: '/assets/raider_w_run1.png' }),
  Object.freeze({ key: 'raider.w.run2', url: '/assets/raider_w_run2.png' }),
  Object.freeze({ key: 'raider.nw.idle', url: '/assets/raider_nw_idle.png' }),
  Object.freeze({ key: 'raider.nw.run1', url: '/assets/raider_nw_run1.png' }),
  Object.freeze({ key: 'raider.nw.run2', url: '/assets/raider_nw_run2.png' }),
  Object.freeze({ key: 'corpSec.n.idle', url: '/assets/corp_n_idle.png' }),
  Object.freeze({ key: 'corpSec.n.run1', url: '/assets/corp_n_run1.png' }),
  Object.freeze({ key: 'corpSec.n.run2', url: '/assets/corp_n_run2.png' }),
  Object.freeze({ key: 'corpSec.ne.idle', url: '/assets/corp_ne_idle.png' }),
  Object.freeze({ key: 'corpSec.ne.run1', url: '/assets/corp_ne_run1.png' }),
  Object.freeze({ key: 'corpSec.ne.run2', url: '/assets/corp_ne_run2.png' }),
  Object.freeze({ key: 'corpSec.e.idle', url: '/assets/corp_e_idle.png' }),
  Object.freeze({ key: 'corpSec.e.run1', url: '/assets/corp_e_run1.png' }),
  Object.freeze({ key: 'corpSec.e.run2', url: '/assets/corp_e_run2.png' }),
  Object.freeze({ key: 'corpSec.se.idle', url: '/assets/corp_se_idle.png' }),
  Object.freeze({ key: 'corpSec.se.run1', url: '/assets/corp_se_run1.png' }),
  Object.freeze({ key: 'corpSec.se.run2', url: '/assets/corp_se_run2.png' }),
  Object.freeze({ key: 'corpSec.s.idle', url: '/assets/corp_s_idle.png' }),
  Object.freeze({ key: 'corpSec.s.run1', url: '/assets/corp_s_run1.png' }),
  Object.freeze({ key: 'corpSec.s.run2', url: '/assets/corp_s_run2.png' }),
  Object.freeze({ key: 'corpSec.sw.idle', url: '/assets/corp_sw_idle.png' }),
  Object.freeze({ key: 'corpSec.sw.run1', url: '/assets/corp_sw_run1.png' }),
  Object.freeze({ key: 'corpSec.sw.run2', url: '/assets/corp_sw_run2.png' }),
  Object.freeze({ key: 'corpSec.w.idle', url: '/assets/corp_w_idle.png' }),
  Object.freeze({ key: 'corpSec.w.run1', url: '/assets/corp_w_run1.png' }),
  Object.freeze({ key: 'corpSec.w.run2', url: '/assets/corp_w_run2.png' }),
  Object.freeze({ key: 'corpSec.nw.idle', url: '/assets/corp_nw_idle.png' }),
  Object.freeze({ key: 'corpSec.nw.run1', url: '/assets/corp_nw_run1.png' }),
  Object.freeze({ key: 'corpSec.nw.run2', url: '/assets/corp_nw_run2.png' }),
  Object.freeze({ key: 'wardenX.idle.0', url: '/assets/boss_idle_0.png' }),
  Object.freeze({ key: 'wardenX.idle.1', url: '/assets/boss_idle_1.png' }),
  Object.freeze({ key: 'wardenX.idle.2', url: '/assets/boss_idle_2.png' }),
  Object.freeze({ key: 'wardenX.idle.3', url: '/assets/boss_idle_3.png' }),
  Object.freeze({ key: 'wardenX.attack.0', url: '/assets/boss_attack_0.png' }),
  Object.freeze({ key: 'wardenX.attack.1', url: '/assets/boss_attack_1.png' }),
  Object.freeze({ key: 'wardenX.attack.2', url: '/assets/boss_attack_2.png' }),
  Object.freeze({ key: 'wardenX.attack.3', url: '/assets/boss_attack_3.png' }),
  Object.freeze({ key: 'environment.floor', url: '/assets/wet_floor.jpg' }),
  Object.freeze({ key: 'environment.crate', url: '/assets/crate.png' }),
  Object.freeze({ key: 'environment.barrel', url: '/assets/barrel.png' }),
  Object.freeze({ key: 'environment.medkit', url: '/assets/medkit.png' }),
  Object.freeze({ key: 'environment.flash', url: '/assets/flash.png' }),
  Object.freeze({ key: 'environment.smoke', url: '/assets/smoke.png' }),
]);

export const DIRS = Object.freeze(['n', 'ne', 'e', 'se', 's', 'sw', 'w', 'nw']);
const byKey = Object.fromEntries(ASSET_ENTRIES.map(({ key, url }) => [key, url]));
const directional = role => Object.fromEntries(DIRS.map(direction => [direction, Object.fromEntries(['idle', 'run1', 'run2'].map(state => [state, byKey[`${role}.${direction}.${state}`]]))]));
export const PLAYER_ASSETS = Object.freeze(directional('raider'));
export const CORP_SEC_ASSETS = Object.freeze(directional('corpSec'));
export const WARDEN_X_IDLE_ASSETS = Object.freeze(Array.from({ length: 4 }, (_, index) => byKey[`wardenX.idle.${index}`]));
export const WARDEN_X_ATTACK_ASSETS = Object.freeze(Array.from({ length: 4 }, (_, index) => byKey[`wardenX.attack.${index}`]));
export const ENVIRONMENT_ASSETS = Object.freeze(Object.fromEntries(['floor', 'crate', 'barrel', 'medkit', 'flash', 'smoke'].map(name => [name, byKey[`environment.${name}`]])));
