import { DIRS, PLAYER_ASSETS as PLAYER_SRC, CORP_SEC_ASSETS as ENEMY_SRC, WARDEN_X_IDLE_ASSETS as BOSS_IDLE_SRC, WARDEN_X_ATTACK_ASSETS as BOSS_ATTACK_SRC, ENVIRONMENT_ASSETS as OTHER_SRC } from './assets.js';

export function startGame() {
const cvs=document.getElementById('game'),ctx=cvs.getContext('2d'),W=360,H=540;
const ui={
 hpText:document.getElementById('hpText'),armText:document.getElementById('armText'),hpFill:document.getElementById('hpFill'),armFill:document.getElementById('armFill'),
 bossHud:document.getElementById('bossHud'),bossFill:document.getElementById('bossFill'),bossPhase:document.getElementById('bossPhase'),stageName:document.getElementById('stageName'),
 objectiveLabel:document.getElementById('objectiveLabel'),objectiveText:document.getElementById('objectiveText'),ammo:document.getElementById('ammo'),reserve:document.getElementById('reserve'),
 status:document.getElementById('status'),grenades:document.getElementById('grenades'),dashCd:document.getElementById('dashCd')
};
const imgs={player:{},enemy:{},bossIdle:[],bossAttack:[],other:{}};
let loadCount=0,total=0;
function loadImage(src,cb){total++;const im=new Image();im.onload=()=>{loadCount++;cb(im);if(loadCount===total)setTimeout(start,0)};im.onerror=()=>{loadCount++;cb(im);if(loadCount===total)setTimeout(start,0)};im.src=src;}
for(const d of DIRS){imgs.player[d]={};imgs.enemy[d]={};for(const st of ['idle','run1','run2']){loadImage(PLAYER_SRC[d][st],im=>imgs.player[d][st]=im);loadImage(ENEMY_SRC[d][st],im=>imgs.enemy[d][st]=im)}}
BOSS_IDLE_SRC.forEach((s,i)=>loadImage(s,im=>imgs.bossIdle[i]=im));BOSS_ATTACK_SRC.forEach((s,i)=>loadImage(s,im=>imgs.bossAttack[i]=im));
for(const [k,s] of Object.entries(OTHER_SRC)) loadImage(s,im=>imgs.other[k]=im);

function start(){
let stage=1,paused=false,dead=false,won=false,transitionT=0,last=0,animT=0,shake=0,fireCd=0,reloadT=0,firing=false,muzzleT=0,kills=0,wave=1;
let ammo=28,reserve=112,grenades=3;
const keys={up:false,down:false,left:false,right:false};
const player={x:180,y:448,r:11,hp:100,maxHp:100,arm:60,maxArm:60,vx:0,vy:0,speed:125,lastDir:'n',aimDir:'n',hitT:0,dashT:0,dashCd:0};
let enemies=[],bullets=[],enemyBullets=[],fx=[],casings=[],rain=[],crates=[],barrels=[],medkits=[];
const boss={x:180,y:196,r:52,hp:1200,maxHp:1200,phase:1,frameT:0,attackT:0,attackFrame:-1,flashT:0,moveT:0,smokeT:0};
let audioCtx=null;
function audio(){if(!audioCtx){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}} return audioCtx;}
function tone(freq,dur=.04,type='square',gain=.02){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur);}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function d2(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function dirFromVec(dx,dy){if(Math.hypot(dx,dy)<.001)return player.lastDir;const a=Math.atan2(dy,dx);let idx=Math.round((a+Math.PI/2)/(Math.PI/4));idx=((idx%8)+8)%8;return DIRS[idx];}
function angleForDir(dir){const i=DIRS.indexOf(dir);return -Math.PI/2+i*Math.PI/4}
function sync(){ui.hpText.textContent=Math.ceil(player.hp)+'/'+player.maxHp;ui.armText.textContent=Math.ceil(player.arm)+'/'+player.maxArm;ui.hpFill.style.width=(100*player.hp/player.maxHp)+'%';ui.armFill.style.width=(100*player.arm/player.maxArm)+'%';ui.ammo.textContent=ammo;ui.reserve.textContent=reserve;ui.grenades.textContent=grenades;ui.dashCd.textContent=player.dashCd>0?player.dashCd.toFixed(1):'READY';if(stage===1){ui.stageName.textContent='AREA 2-3A';ui.bossHud.classList.remove('show');ui.objectiveLabel.textContent='⚠ CLEAR THE SECTOR';ui.objectiveText.textContent=kills+' / 6'}else{ui.stageName.textContent='AREA 2-3B';ui.bossHud.classList.add('show');ui.objectiveLabel.textContent='⚠ DEFEAT WARDEN-X';ui.objectiveText.textContent='PHASE '+boss.phase;ui.bossFill.style.width=(100*boss.hp/boss.maxHp)+'%';ui.bossPhase.textContent='PHASE '+boss.phase}}
function initRain(){rain=[];for(let i=0;i<70;i++)rain.push({x:Math.random()*W,y:Math.random()*H,s:70+Math.random()*100,l:5+Math.random()*9,a:.08+Math.random()*.16})}
function spawnEnemy(x,y,role='rifle'){enemies.push({x,y,r:10,hp:72,maxHp:72,speed:role==='heavy'?33:43,shootCd:.5+Math.random(),burst:0,burstCd:0,state:'seek',dir:'s',moveDir:'s',hitT:0,deadT:0,role,strafe:Math.random()<.5?-1:1})}
function setupStage1(){stage=1;kills=0;wave=1;transitionT=0;enemies=[];bullets=[];enemyBullets=[];fx=[];casings=[];crates=[{x:78,y:246,w:63,h:62},{x:230,y:277,w:68,h:65},{x:150,y:155,w:66,h:64}];barrels=[{x:300,y:188,r:18,hp:3,alive:true},{x:48,y:354,r:18,hp:3,alive:true}];medkits=[{x:55,y:448,alive:true}];player.x=180;player.y=460;player.vx=player.vy=0;spawnEnemy(68,105);spawnEnemy(285,110);spawnEnemy(285,405);ui.status.textContent='Этап 1: первая группа Corp Sec. Укрытия блокируют пули.';sync()}
function setupBoss(){stage=2;transitionT=0;enemies=[];bullets=[];enemyBullets=[];fx=[];casings=[];crates=[];barrels=[];medkits=[{x:48,y:425,alive:true},{x:310,y:405,alive:true}];player.x=180;player.y=468;player.vx=player.vy=0;player.hp=Math.min(player.maxHp,player.hp+28);player.arm=Math.min(player.maxArm,player.arm+20);boss.x=180;boss.y=195;boss.hp=boss.maxHp;boss.phase=1;boss.frameT=0;boss.attackT=.8;boss.attackFrame=-1;boss.flashT=0;boss.moveT=0;boss.smokeT=0;ui.status.textContent='Этап 2: Warden-X ожил. Следи за красными зонами и паттернами пуль.';sync()}
function resetAll(){dead=false;won=false;paused=false;ammo=28;reserve=112;grenades=3;player.hp=100;player.arm=60;player.hitT=0;player.dashT=0;player.dashCd=0;document.getElementById('pause').textContent='PAUSE';setupStage1()}
function rectCircleHit(o,r){const nx=clamp(o.x,r.x,r.x+r.w),ny=clamp(o.y,r.y,r.y+r.h);return Math.hypot(o.x-nx,o.y-ny)<o.r}
function blocked(o,x,y){if(x-o.r<13||x+o.r>347||y-o.r<60||y+o.r>520)return true;if(stage===1){const q={x,y,r:o.r};if(crates.some(c=>rectCircleHit(q,c)))return true;if(barrels.some(b=>b.alive&&Math.hypot(x-b.x,y-b.y)<o.r+b.r-2))return true}return false}
function move(o,dx,dy){const ox=o.x,oy=o.y;o.x+=dx;if(blocked(o,o.x,o.y))o.x=ox;o.y+=dy;if(blocked(o,o.x,o.y))o.y=oy;return Math.hypot(o.x-ox,o.y-oy)}
function visible(a,b){if(stage!==1)return true;const steps=Math.ceil(Math.hypot(a.x-b.x,a.y-b.y)/8);for(let i=1;i<steps;i++){const t=i/steps,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;if(crates.some(c=>x>c.x&&x<c.x+c.w&&y>c.y&&y<c.y+c.h))return false;if(barrels.some(br=>br.alive&&Math.hypot(x-br.x,y-br.y)<br.r))return false}return true}
function nearestTarget(){if(stage===2)return boss;let best=null,bd=1e9;for(const e of enemies)if(e.deadT<=0){const dd=d2(player,e);if(dd<bd&&visible(player,e)){best=e;bd=dd}}return best}
function reload(){if(reloadT>0||ammo===28||reserve<=0)return;reloadT=.82;ui.status.textContent='RELOADING…';tone(320,.05,'square',.012)}
function fire(){if(paused||dead||won||fireCd>0||reloadT>0)return;if(ammo<=0){reload();return}const t=nearestTarget();if(!t)return;const ty=stage===2?t.y+25:t.y;const a=Math.atan2(ty-(player.y-12),t.x-player.x);player.aimDir=dirFromVec(Math.cos(a),Math.sin(a));bullets.push({x:player.x+Math.cos(a)*15,y:player.y-13+Math.sin(a)*8,vx:Math.cos(a)*350,vy:Math.sin(a)*350,life:1.35,dmg:stage===2?17:26});casings.push({x:player.x,y:player.y-8,vx:-Math.sin(a)*(35+Math.random()*28),vy:-30-Math.random()*35,life:.65});ammo--;fireCd=.105;muzzleT=.06;tone(90,.035,'sawtooth',.018);sync()}
function enemyShot(e){const a=Math.atan2(player.y-e.y,player.x-e.x)+(Math.random()-.5)*.045;e.dir=dirFromVec(Math.cos(a),Math.sin(a));enemyBullets.push({x:e.x+Math.cos(a)*13,y:e.y-8+Math.sin(a)*7,vx:Math.cos(a)*145,vy:Math.sin(a)*145,life:2.7,r:3,dmg:e.role==='heavy'?13:9});tone(70,.03,'square',.008)}
function damagePlayer(n){if(player.hitT>0||player.dashT>0||dead)return;let rem=n;if(player.arm>0){const a=Math.min(rem,player.arm);player.arm-=a;rem-=a}player.hp-=rem;player.hitT=.28;shake=4;tone(45,.08,'sawtooth',.02);if(player.hp<=0){player.hp=0;dead=true;paused=true;ui.status.textContent='RAID FAILED — нажми RESTART GAME'}sync()}
function killEnemy(e){if(e.deadT>0)return;e.deadT=.55;kills++;fx.push({type:'burst',x:e.x,y:e.y,r:4,max:28,life:.3});tone(52,.08,'square',.018);if(stage===1&&kills===3&&wave===1){wave=2;setTimeout(()=>{if(stage===1&&!dead){spawnEnemy(48,115);spawnEnemy(307,116);spawnEnemy(305,365,'heavy');ui.status.textContent='Вторая группа вошла в сектор.'}},450)}if(stage===1&&kills>=6){transitionT=2.0;ui.status.textContent='SECTOR CLEAR — доступ к реактору открыт.'}sync()}
function explode(x,y,r=82,bossDmg=0){fx.push({type:'explosion',x,y,r:5,max:r,life:.45});shake=Math.max(shake,7);tone(38,.16,'sawtooth',.035);for(const e of enemies)if(e.deadT<=0&&Math.hypot(e.x-x,e.y-y)<r){e.hp-=100;if(e.hp<=0)killEnemy(e)}if(stage===2&&Math.hypot(boss.x-x,boss.y+25-y)<r+boss.r&&bossDmg){boss.hp-=bossDmg;boss.flashT=.12;if(boss.hp<=0)winBoss()}if(Math.hypot(player.x-x,player.y-y)<r*.62)damagePlayer(18)}
function grenade(){if(paused||dead||won||grenades<=0)return;grenades--;const t=nearestTarget();explode(t?t.x:player.x,t?(stage===2?t.y+25:t.y):player.y-65,90,105);sync()}
function dash(){if(paused||dead||won||player.dashCd>0)return;let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);if(!dx&&!dy){const a=angleForDir(player.lastDir);dx=Math.cos(a);dy=Math.sin(a)}const l=Math.hypot(dx,dy)||1;const nx=clamp(player.x+dx/l*62,18,342),ny=clamp(player.y+dy/l*62,70,508);if(!blocked(player,nx,ny)){player.x=nx;player.y=ny}player.dashT=.15;player.dashCd=1.45;fx.push({type:'dash',x:player.x,y:player.y,r:4,max:36,life:.22});tone(190,.06,'triangle',.02);sync()}
function bossBurst(count=5,spread=.68,speed=160){const a=Math.atan2(player.y-(boss.y+35),player.x-boss.x);for(let i=0;i<count;i++){const off=(i-(count-1)/2)*(spread/Math.max(1,count-1));enemyBullets.push({x:boss.x,y:boss.y+48,vx:Math.cos(a+off)*speed,vy:Math.sin(a+off)*speed,life:3.4,r:4,dmg:10})}boss.attackFrame=0;boss.flashT=.1;tone(50,.07,'sawtooth',.025)}
function bossRadial(count=12,speed=128){for(let i=0;i<count;i++){const a=i/count*Math.PI*2+boss.moveT*.4;enemyBullets.push({x:boss.x,y:boss.y+40,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:3.6,r:4,dmg:9})}boss.attackFrame=2;boss.flashT=.1}
function dangerZone(x,y,r=30,delay=.9){fx.push({type:'zone',x,y,r,max:r,life:delay+.22,delay,boom:false})}
function bossPattern(){if(stage!==2||won)return;boss.phase=boss.hp<400?3:boss.hp<800?2:1;if(boss.phase===1){bossBurst(5,.72,165);if(Math.random()<.65)dangerZone(clamp(player.x+(Math.random()-.5)*55,35,325),clamp(player.y+(Math.random()-.5)*30,280,490),30,1.0);boss.attackT=.82}else if(boss.phase===2){Math.random()<.5?bossBurst(7,.98,178):bossRadial(11,136);dangerZone(clamp(player.x+(Math.random()-.5)*75,32,328),clamp(player.y+(Math.random()-.5)*46,275,492),32,.82);boss.attackT=.68}else{Math.random()<.48?bossRadial(15,146):bossBurst(9,1.22,188);dangerZone(clamp(player.x+(Math.random()-.5)*90,30,330),clamp(player.y+(Math.random()-.5)*54,270,494),34,.65);dangerZone(clamp(player.x+(Math.random()-.5)*90,30,330),clamp(player.y+(Math.random()-.5)*54,270,494),28,.78);boss.attackT=.54}sync()}
function winBoss(){if(won)return;boss.hp=0;won=true;paused=true;ui.status.textContent='WARDEN-X DESTROYED — TWO-STAGE RAID COMPLETE';tone(260,.3,'sawtooth',.035);sync()}
function hitCover(b){if(stage!==1)return null;for(const c of crates)if(b.x>c.x&&b.x<c.x+c.w&&b.y>c.y&&b.y<c.y+c.h)return 'crate';for(const br of barrels)if(br.alive&&Math.hypot(b.x-br.x,b.y-br.y)<br.r)return br;return null}
function update(dt){if(paused)return;animT+=dt;shake=Math.max(0,shake-dt*17);fireCd=Math.max(0,fireCd-dt);muzzleT=Math.max(0,muzzleT-dt);player.hitT=Math.max(0,player.hitT-dt);player.dashT=Math.max(0,player.dashT-dt);player.dashCd=Math.max(0,player.dashCd-dt);
if(reloadT>0){reloadT-=dt;if(reloadT<=0){const need=28-ammo,take=Math.min(need,reserve);ammo+=take;reserve-=take;ui.status.textContent=stage===1?'Сектор активен.':'Warden-X: '+Math.ceil(boss.hp)+' HP';sync()}}
if(firing)fire();
let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);const accel=520,friction=8;if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l;player.lastDir=dirFromVec(dx,dy);player.vx+=dx*accel*dt;player.vy+=dy*accel*dt}player.vx*=Math.max(0,1-friction*dt);player.vy*=Math.max(0,1-friction*dt);const sp=Math.hypot(player.vx,player.vy),maxSp=player.speed*(player.dashT>0?1.6:1);if(sp>maxSp){player.vx=player.vx/sp*maxSp;player.vy=player.vy/sp*maxSp}move(player,player.vx*dt,player.vy*dt);
if(stage===1){for(const e of enemies){if(e.deadT>0){e.deadT-=dt;continue}e.hitT=Math.max(0,e.hitT-dt);e.shootCd-=dt;e.burstCd-=dt;const a=Math.atan2(player.y-e.y,player.x-e.x),dd=d2(e,player),los=visible(e,player);let mvx=0,mvy=0;let sepX=0,sepY=0;for(const o of enemies)if(o!==e&&o.deadT<=0){const xx=e.x-o.x,yy=e.y-o.y,dist=Math.hypot(xx,yy);if(dist>0&&dist<34){sepX+=xx/dist;sepY+=yy/dist}}if(!los||dd>165){mvx=Math.cos(a)+sepX*.65;mvy=Math.sin(a)+sepY*.65;e.state='seek'}else if(dd<95){mvx=-Math.cos(a)+sepX*.8;mvy=-Math.sin(a)+sepY*.8;e.state='back'}else{mvx=Math.cos(a+e.strafe*Math.PI/2)*.75+sepX*.6;mvy=Math.sin(a+e.strafe*Math.PI/2)*.75+sepY*.6;e.state='strafe'}const ml=Math.hypot(mvx,mvy)||1;if(e.burst<=0){move(e,mvx/ml*e.speed*dt,mvy/ml*e.speed*dt);e.moveDir=dirFromVec(mvx,mvy)}e.dir=dirFromVec(Math.cos(a),Math.sin(a));if(los&&dd<220&&e.shootCd<=0){e.burst=e.role==='heavy'?3:2;e.burstCd=0;e.shootCd=e.role==='heavy'?1.65:1.35+Math.random()*.35}if(e.burst>0&&e.burstCd<=0){enemyShot(e);e.burst--;e.burstCd=.16}}}
else{boss.moveT+=dt;boss.frameT+=dt;boss.attackT-=dt;boss.flashT=Math.max(0,boss.flashT-dt);boss.x=180+Math.sin(boss.moveT*.85)*(boss.phase===3?48:34);boss.y=193+Math.sin(boss.moveT*1.45)*5;if(boss.attackT<=0)bossPattern();if(boss.attackFrame>=0){boss.attackFrame=(boss.attackFrame+dt*8);if(boss.attackFrame>=4)boss.attackFrame=-1}if(boss.phase>=2){boss.smokeT+=dt;if(boss.smokeT>.22){boss.smokeT=0;fx.push({type:'smoke',x:boss.x+(Math.random()-.5)*45,y:boss.y-55+Math.random()*30,r:10,max:30,life:.65})}}}
for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;const cov=hitCover(b);if(cov){b.life=0;if(cov!=='crate'){cov.hp--;if(cov.hp<=0){cov.alive=false;explode(cov.x,cov.y,90,0)}}continue}if(stage===1){for(const e of enemies)if(e.deadT<=0&&Math.hypot(b.x-e.x,b.y-e.y)<13){b.life=0;e.hp-=b.dmg;e.hitT=.1;fx.push({type:'hit',x:b.x,y:b.y,r:3,max:13,life:.13});if(e.hp<=0)killEnemy(e);break}}else if(Math.hypot(b.x-boss.x,b.y-(boss.y+20))<boss.r+7){b.life=0;boss.hp-=b.dmg;boss.flashT=.06;fx.push({type:'hit',x:b.x,y:b.y,r:3,max:16,life:.14});if(boss.hp<=0)winBoss();sync()}}
bullets=bullets.filter(b=>b.life>0&&b.x>-20&&b.x<W+20&&b.y>-20&&b.y<H+20);
for(const b of enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;const cov=hitCover(b);if(cov){b.life=0;continue}if(Math.hypot(b.x-player.x,b.y-player.y)<player.r+b.r){b.life=0;damagePlayer(b.dmg)}}enemyBullets=enemyBullets.filter(b=>b.life>0&&b.x>-25&&b.x<W+25&&b.y>-25&&b.y<H+25);
for(const m of medkits)if(m.alive&&Math.hypot(player.x-m.x,player.y-m.y)<27){m.alive=false;player.hp=Math.min(player.maxHp,player.hp+32);ui.status.textContent='+32 HP';sync()}
for(const f of fx){f.life-=dt;if(f.type==='zone'){f.delay-=dt;if(f.delay<=0&&!f.boom){f.boom=true;explode(f.x,f.y,f.r+20,0)}}else f.r+=(f.max-f.r)*Math.min(1,dt*12)}fx=fx.filter(f=>f.life>0);
for(const c of casings){c.vy+=90*dt;c.x+=c.vx*dt;c.y+=c.vy*dt;c.life-=dt}casings=casings.filter(c=>c.life>0);
for(const r of rain){r.y+=r.s*dt;r.x-=r.s*.18*dt;if(r.y>H+10){r.y=-10;r.x=Math.random()*W}if(r.x<-10)r.x=W+10}
if(stage===1&&transitionT>0){transitionT-=dt;if(transitionT<=0)setupBoss()}sync()}
function drawFloor(){const pat=ctx.createPattern(imgs.other.floor,'repeat');ctx.fillStyle=pat;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(3,7,11,.36)';ctx.fillRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'rgba(0,196,220,.13)');g.addColorStop(.55,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(230,35,96,.14)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawStage1Bg(){drawFloor();ctx.fillStyle='rgba(5,9,13,.92)';ctx.fillRect(0,0,W,58);ctx.fillStyle='#171e24';ctx.fillRect(0,54,W,7);ctx.fillStyle='#24cad6';ctx.fillRect(16,54,92,2);ctx.fillStyle='#ee354d';ctx.fillRect(252,54,92,2);ctx.fillStyle='#11181e';ctx.fillRect(0,60,17,H-60);ctx.fillRect(W-17,60,17,H-60);for(let y=80;y<H;y+=52){ctx.fillStyle='#26323a';ctx.fillRect(3,y,11,3);ctx.fillRect(W-14,y,11,3)}ctx.fillStyle='#0a1015';ctx.fillRect(128,60,104,50);ctx.strokeStyle='#3c4b54';ctx.strokeRect(130,62,100,46);ctx.fillStyle=transitionT>0?'#2ce09c':'#d63b48';ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.fillText(transitionT>0?'REACTOR OPEN':'LOCKED',180,90);ctx.textAlign='left';}
function drawBossBg(){drawFloor();ctx.fillStyle='rgba(4,6,8,.53)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#11171c';ctx.fillRect(0,0,W,64);ctx.fillStyle='#151b20';ctx.fillRect(0,64,42,170);ctx.fillRect(W-42,64,42,170);ctx.strokeStyle='rgba(238,48,65,.42)';ctx.lineWidth=10;ctx.beginPath();ctx.arc(180,155,87,Math.PI*.12,Math.PI*.88);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='rgba(255,62,77,.76)';ctx.beginPath();ctx.arc(180,155,76,Math.PI*.12,Math.PI*.88);ctx.stroke();ctx.fillStyle='rgba(255,45,60,.13)';ctx.fillRect(174,65,12,120);ctx.fillStyle='#e73c4d';ctx.font='bold 9px monospace';ctx.fillText('REACTOR 03',10,92);ctx.fillText('CORE OVERLOAD',266,92);}
function drawBottom(im,x,y,h,alpha=1){const w=im.width*(h/im.height);ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x-w/2,y-h,w,h);ctx.restore()}
function playerImage(){const moving=Math.hypot(player.vx,player.vy)>13;let dir=moving?player.lastDir:player.lastDir;if(firing||muzzleT>0)dir=player.aimDir;const st=moving?(Math.floor(animT*10)%2?'run1':'run2'):'idle';return imgs.player[dir][st]}
function enemyImage(e){const moving=e.burst<=0;const dir=e.burst>0?e.dir:e.moveDir;const st=moving?(Math.floor((animT+e.x*.01)*8)%2?'run1':'run2'):'idle';return imgs.enemy[dir][st]}
function drawMuzzle(x,y,dir,size=34){const a=angleForDir(dir);ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.globalCompositeOperation='lighter';ctx.drawImage(imgs.other.flash,15,-size*.28,size*1.25,size*.56);ctx.restore()}
function drawActorShadow(x,y,r,col){ctx.save();ctx.fillStyle=col;ctx.globalAlpha=.22;ctx.beginPath();ctx.ellipse(x,y+7,r*1.35,r*.55,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);stage===1?drawStage1Bg():drawBossBg();
if(stage===1){for(const c of crates){ctx.save();ctx.shadowColor='#21cbd6';ctx.shadowBlur=8;drawBottom(imgs.other.crate,c.x+c.w/2,c.y+c.h+8,c.h+34);ctx.restore()}for(const br of barrels)if(br.alive){ctx.save();ctx.shadowColor='#ff3045';ctx.shadowBlur=12;drawBottom(imgs.other.barrel,br.x,br.y+27,66);ctx.restore()}}
if(stage===2){const idleFrame=Math.floor(boss.frameT*5)%4;let im=imgs.bossIdle[idleFrame];if(boss.attackFrame>=0)im=imgs.bossAttack[Math.min(3,Math.floor(boss.attackFrame))];ctx.save();if(boss.flashT>0)ctx.globalAlpha=.6;ctx.shadowColor='#ff243f';ctx.shadowBlur=14;drawBottom(im,boss.x,boss.y+118,250);ctx.restore();}
for(const m of medkits)if(m.alive){ctx.save();ctx.shadowColor='#1af0b2';ctx.shadowBlur=14;drawBottom(imgs.other.medkit,m.x,m.y+20,48);ctx.restore()}
if(stage===1){const actors=[...enemies.filter(e=>e.deadT<=0).map(e=>({y:e.y,type:'e',o:e})),{y:player.y,type:'p',o:player}].sort((a,b)=>a.y-b.y);for(const a of actors){if(a.type==='e'){const e=a.o;drawActorShadow(e.x,e.y,11,'#ff334c');drawBottom(enemyImage(e),e.x,e.y+20,62,e.hitT>0?.65:1);ctx.fillStyle='#351016';ctx.fillRect(e.x-17,e.y-35,34,3);ctx.fillStyle='#f03c51';ctx.fillRect(e.x-17,e.y-35,34*Math.max(0,e.hp/e.maxHp),3);if(e.burst>0)drawMuzzle(e.x,e.y-12,e.dir,30)}else{drawActorShadow(player.x,player.y,12,'#25d8e0');drawBottom(playerImage(),player.x,player.y+21,67,player.hitT>0&&Math.floor(player.hitT*22)%2===0?.45:(player.dashT>0?.72:1));}}}
else{drawActorShadow(player.x,player.y,12,'#25d8e0');drawBottom(playerImage(),player.x,player.y+21,67,player.hitT>0&&Math.floor(player.hitT*22)%2===0?.45:(player.dashT>0?.72:1));}
if(muzzleT>0)drawMuzzle(player.x,player.y-12,player.aimDir,34);
ctx.save();ctx.globalCompositeOperation='lighter';for(const b of bullets){ctx.strokeStyle='#ffd75a';ctx.lineWidth=2.4;ctx.beginPath();ctx.moveTo(b.x-b.vx*.026,b.y-b.vy*.026);ctx.lineTo(b.x,b.y);ctx.stroke()}for(const b of enemyBullets){ctx.fillStyle=stage===2?'#ff3954':'#ff4355';ctx.shadowColor='#ff334b';ctx.shadowBlur=7;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.restore();
for(const c of casings){ctx.save();ctx.globalAlpha=Math.max(0,c.life*1.5);ctx.translate(c.x,c.y);ctx.rotate(c.life*13);ctx.fillStyle='#c79d36';ctx.fillRect(-3,-1,6,2);ctx.restore()}
for(const f of fx){if(f.type==='zone'){ctx.save();const pulse=.35+.2*Math.sin(f.life*22);ctx.globalAlpha=pulse;ctx.fillStyle='#f52947';ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.8;ctx.strokeStyle='#ff5b68';ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.stroke();ctx.restore()}else if(f.type==='smoke'){ctx.save();ctx.globalAlpha=Math.max(0,f.life*.55);drawBottom(imgs.other.smoke,f.x,f.y+f.r,40+f.r);ctx.restore()}else{ctx.save();ctx.globalAlpha=Math.max(0,f.life*2.3);ctx.strokeStyle=f.type==='dash'?'#36dce6':'#ffb038';ctx.lineWidth=4;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#ef3b52';ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,f.r*.62,0,Math.PI*2);ctx.stroke();ctx.restore()}}
for(const r of rain){ctx.strokeStyle='rgba(121,211,232,'+r.a+')';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-2,r.y+r.l);ctx.stroke()}
ctx.restore();
if(transitionT>0){ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(40,224,280,88);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='bold 18px monospace';ctx.fillText('SECTOR CLEAR',180,258);ctx.fillStyle='#35d8e2';ctx.font='9px monospace';ctx.fillText('ENTERING REACTOR CORE…',180,283);ctx.textAlign='left'}
if(paused){ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(45,226,270,92);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='bold 18px monospace';ctx.fillText(won?'RAID COMPLETE':dead?'RAID FAILED':'PAUSED',180,260);ctx.font='9px monospace';ctx.fillStyle='#a3b5bd';ctx.fillText(won?'WARDEN-X DESTROYED':dead?'RESTART GAME':'PRESS PLAY',180,285);ctx.textAlign='left'}}
function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
document.querySelectorAll('[data-dir]').forEach(btn=>{const k=btn.dataset.dir;const on=e=>{e.preventDefault();audio();keys[k]=true;btn.classList.add('on')};const off=e=>{if(e)e.preventDefault();keys[k]=false;btn.classList.remove('on')};btn.addEventListener('pointerdown',on);btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off);btn.addEventListener('pointerleave',off)});
const fireBtn=document.getElementById('fire');const fireOn=e=>{e.preventDefault();audio();firing=true;fireBtn.classList.add('on');fire()};const fireOff=e=>{if(e)e.preventDefault();firing=false;fireBtn.classList.remove('on')};fireBtn.addEventListener('pointerdown',fireOn);fireBtn.addEventListener('pointerup',fireOff);fireBtn.addEventListener('pointercancel',fireOff);fireBtn.addEventListener('pointerleave',fireOff);
document.getElementById('dash').addEventListener('click',()=>{audio();dash()});document.getElementById('grenade').addEventListener('click',()=>{audio();grenade()});document.getElementById('pause').addEventListener('click',e=>{if(!dead&&!won){paused=!paused;e.currentTarget.textContent=paused?'PLAY':'PAUSE'}});document.getElementById('reset').addEventListener('click',resetAll);
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='w'||e.key==='ArrowUp')keys.up=true;if(k==='s'||e.key==='ArrowDown')keys.down=true;if(k==='a'||e.key==='ArrowLeft')keys.left=true;if(k==='d'||e.key==='ArrowRight')keys.right=true;if(e.code==='Space'){firing=true;fire();e.preventDefault()}if(k==='g')grenade();if(e.key==='Shift')dash()});document.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='w'||e.key==='ArrowUp')keys.up=false;if(k==='s'||e.key==='ArrowDown')keys.down=false;if(k==='a'||e.key==='ArrowLeft')keys.left=false;if(k==='d'||e.key==='ArrowRight')keys.right=false;if(e.code==='Space')firing=false});
window.addEventListener('blur',()=>{paused=true;firing=false;document.getElementById('pause').textContent='PLAY'});
window.__NEON_TEST={get:()=>({stage,x:player.x,y:player.y,ammo,bossHp:boss.hp,kills,paused,dead,won}),skipToBoss:()=>setupBoss(),completeStage1:()=>{kills=6;transitionT=.05;sync()},damageBoss:(n=100)=>{boss.hp=Math.max(0,boss.hp-n);if(boss.hp<=0)winBoss();sync()}};
initRain();resetAll();window.__NEON_READY=true;requestAnimationFrame(loop);
}
}
