import assert from 'node:assert/strict';
import test from 'node:test';
import { MultiplayerBossSimulation } from '../src/game/multiplayer/MultiplayerBossSimulation.js';
import { DANGER_CONFIG, MULTIPLAYER_TICK_DT, MULTIPLAYER_TICK_HZ } from '../src/game/multiplayer/config.js';
import { createSeededRng } from '../src/game/simulation/rng.js';

const create = (seed = 7) => new MultiplayerBossSimulation({ rng: createSeededRng(seed) });
const stepFor = (g, seconds, dt = .02) => { for (let t = 0; t < seconds; t += dt) g.step(dt); };
const player = (g, slot) => g.getSnapshot().players[slot - 1];
const fireOnce = (g, slot) => { g.applyCommand(slot, { type: 'fire', active: true }); g.step(0); g.applyCommand(slot, { type: 'fire', active: false }); };
const eventTypes = g => g.drainEvents().map(event => event.type);

test('1 starts with exactly slots 1 and 2', () => assert.deepEqual(create().getSnapshot().players.map(p => p.slot), [1, 2]));
test('2 players own independent resource values', () => { const g=create();g.state.players[0].ammo=3;assert.equal(player(g,2).ammo,28); });
test('3 snapshots keep deterministic slot ordering', () => assert.deepEqual(create().getSnapshot().players.map(p=>p.slot),[1,2]));
test('4 slot 1 movement leaves slot 2 still', () => { const g=create(),x=player(g,2).x;g.applyCommand(1,{type:'move',x:1,y:0});stepFor(g,.2);assert.equal(player(g,2).x,x);assert.ok(player(g,1).x>145); });
test('5 slot 2 movement leaves slot 1 still', () => { const g=create(),x=player(g,1).x;g.applyCommand(2,{type:'move',x:-1,y:0});stepFor(g,.2);assert.equal(player(g,1).x,x);assert.ok(player(g,2).x<215); });
test('6 simultaneous movement advances both', () => { const g=create();g.applyCommand(1,{type:'move',x:-1,y:0});g.applyCommand(2,{type:'move',x:1,y:0});stepFor(g,.2);assert.ok(player(g,1).x<145);assert.ok(player(g,2).x>215); });
test('7 slot 1 firing consumes only slot 1 ammo', () => { const g=create();fireOnce(g,1);assert.deepEqual(g.getSnapshot().players.map(p=>p.ammo),[27,28]); });
test('8 slot 2 firing consumes only slot 2 ammo', () => { const g=create();fireOnce(g,2);assert.deepEqual(g.getSnapshot().players.map(p=>p.ammo),[28,27]); });
test('9 bullets have owner slot and stable IDs', () => { const g=create();fireOnce(g,1);fireOnce(g,2);assert.deepEqual(g.getSnapshot().bullets.map(b=>[b.ownerSlot,b.id]),[[1,'bullet-1'],[2,'bullet-2']]); });
test('10 automatic reload is per-player', () => { const g=create();g.state.players[0].ammo=0;g.applyCommand(1,{type:'fire',active:true});g.step(0);g.applyCommand(1,{type:'fire',active:false});assert.equal(player(g,1).reloadTimer,.82);assert.equal(player(g,2).reloadTimer,0);stepFor(g,.84);assert.equal(player(g,1).ammo,28);assert.equal(player(g,1).reserveAmmo,84); });
test('11 dash cooldown is per-player', () => { const g=create();g.applyCommand(1,{type:'dash'});g.step(0);assert.equal(player(g,1).dashCooldown,1.45);assert.equal(player(g,2).dashCooldown,0); });
test('12 grenade consumption is independent', () => { const g=create();g.applyCommand(2,{type:'grenade'});g.step(0);assert.deepEqual(g.getSnapshot().players.map(p=>p.grenades),[3,2]); });
test('13 grenade damages the shared boss', () => { const g=create();g.applyCommand(1,{type:'grenade'});g.step(0);assert.equal(g.getSnapshot().boss.hp,1095); });
test('14 Raider attacks never friendly-fire', () => { const g=create();g.state.players[0].x=g.state.players[1].x;g.state.players[0].y=g.state.players[1].y;g.applyCommand(1,{type:'grenade'});g.step(0);assert.equal(player(g,2).hp,100); });
test('15 armor absorbs damage before HP', () => { const g=create();g.damagePlayer(1,70);assert.equal(player(g,1).armor,0);assert.equal(player(g,1).hp,90); });
test('16 one Raider death leaves match active', () => { const g=create();g.damagePlayer(1,200);assert.equal(g.getSnapshot().status,'active');assert.equal(player(g,2).alive,true); });
test('17 dead Raider stops attacking', () => { const g=create();g.applyCommand(1,{type:'fire',active:true});g.damagePlayer(1,200);g.step(.02);assert.equal(g.getSnapshot().bullets.length,0);assert.equal(player(g,1).firing,false); });
test('18 dead Raider is excluded from boss targeting', () => { const g=create();g.damagePlayer(1,200);g.state.boss.attackTimer=0;g.step(0);assert.ok(g.getSnapshot().enemyBullets.every(b=>b.targetSlot===2)); });
test('19 both deaths emit match-lost exactly once', () => { const g=create();g.drainEvents();g.damagePlayer(1,200);g.damagePlayer(2,200);g.damagePlayer(2,200);assert.equal(eventTypes(g).filter(x=>x==='match-lost').length,1);assert.equal(g.getSnapshot().status,'lost'); });
test('20 both players damage one canonical boss', () => { const g=create();g.applyCommand(1,{type:'grenade'});g.applyCommand(2,{type:'grenade'});g.step(0);assert.equal(g.getSnapshot().boss.hp,990); });
test('21 boss starts at exactly 1200 HP', () => assert.equal(create().getSnapshot().boss.hp,1200));
test('22 phase threshold activation waits for pattern boundary', () => { const g=create();g.damageBoss(401);assert.equal(g.getSnapshot().boss.phase,1);g.step(.02);assert.equal(g.getSnapshot().boss.phase,1);stepFor(g,.8);assert.equal(g.getSnapshot().boss.phase,2); });
test('23 danger phase bounds/configuration remain exact', () => { assert.deepEqual(DANGER_CONFIG[1],[{xRange:55,yRange:30,minX:35,maxX:325,minY:280,maxY:490,radius:30,delay:1}]);assert.deepEqual(DANGER_CONFIG[2],[{xRange:75,yRange:46,minX:32,maxX:328,minY:275,maxY:492,radius:32,delay:.82}]);assert.deepEqual(DANGER_CONFIG[3].map(z=>[z.minX,z.maxX,z.minY,z.maxY,z.xRange,z.yRange,z.radius,z.delay]),[[30,330,270,494,90,54,34,.65],[30,330,270,494,90,54,28,.78]]); });
test('24 burst deterministically alternates living targets', () => { const g=create();g.state.boss.attackTimer=0;g.step(0);assert.equal(g.getSnapshot().enemyBullets[0].targetSlot,1);g.state.boss.attackTimer=0;g.step(0);assert.equal(g.getSnapshot().enemyBullets.at(-1).targetSlot,1); /* danger placement consumes slot 2 */ });
test('25 boss projectile can damage slot 1', () => { const g=create();g.state.enemyBullets.push({id:'enemy-bullet-1',x:145,y:468,vx:0,vy:0,life:1,radius:4,damage:10});g.step(0);assert.equal(player(g,1).armor,50); });
test('26 boss projectile can damage slot 2', () => { const g=create();g.state.enemyBullets.push({id:'enemy-bullet-1',x:215,y:468,vx:0,vy:0,life:1,radius:4,damage:10});g.step(0);assert.equal(player(g,2).armor,50); });
test('27 medkits are globally consumed once', () => { const g=create();g.state.players.forEach(p=>{p.hp=50;p.x=48;p.y=425});g.step(0);assert.equal(player(g,1).hp,82);assert.equal(player(g,2).hp,50);assert.equal(g.getSnapshot().medkits[0].alive,false); });
test('28 zero boss HP produces won status', () => { const g=create();g.damageBoss(1200);assert.equal(g.getSnapshot().status,'won'); });
test('29 victory events emit exactly once', () => { const g=create();g.drainEvents();g.damageBoss(1200);g.damageBoss(1);const e=eventTypes(g);assert.equal(e.filter(x=>x==='boss-defeated').length,1);assert.equal(e.filter(x=>x==='match-won').length,1); });
test('30 snapshots JSON serialize', () => assert.doesNotThrow(()=>JSON.stringify(create().getSnapshot())));
test('31 events JSON serialize and drain ownership is exclusive', () => { const g=create();assert.doesNotThrow(()=>JSON.stringify(g.drainEvents()));assert.deepEqual(g.drainEvents(),[]); });
test('32 snapshot mutation cannot alter canonical state', () => { const g=create(),s=g.getSnapshot();s.players[0].hp=1;assert.equal(player(g,1).hp,100); });
const deterministicRun = () => { const g=create(99),events=[];for(let i=0;i<100;i++){if(i===0){g.applyCommand(1,{type:'move',x:1,y:-1});g.applyCommand(2,{type:'fire',active:true});}if(i===12)g.applyCommand(1,{type:'grenade'});g.step(.016);events.push(...g.drainEvents());}return [g.getSnapshot(),events]; };
test('33 same seed, commands, and dt produce equal snapshots', () => assert.deepEqual(deterministicRun()[0],deterministicRun()[0]));
test('34 same seed, commands, and dt produce equal event history', () => assert.deepEqual(deterministicRun()[1],deterministicRun()[1]));
test('35 dynamic IDs are unique and deterministic', () => { const ids=deterministicRun()[0];const all=[...ids.bullets,...ids.enemyBullets,...ids.dangerZones].map(x=>x.id);assert.equal(new Set(all).size,all.length);assert.deepEqual(all,deterministicRun()[0].bullets.concat(deterministicRun()[0].enemyBullets,deterministicRun()[0].dangerZones).map(x=>x.id)); });
test('36 invalid slot is rejected', () => assert.throws(()=>create().applyCommand(3,{type:'dash'}),/slot/));
test('37 invalid remote command is rejected', () => assert.throws(()=>create().applyCommand(1,{type:'reload'}),/invalid/));
test('38 commands reject dt and state injection fields', () => { const g=create();for(const command of [{type:'move',x:1,y:0,dt:.1},{type:'fire',active:true,hp:0},{type:'grenade',damage:999},{type:'dash',position:{x:1,y:1}}])assert.throws(()=>g.applyCommand(1,command),/invalid/); });
test('fixed authoritative tick contract is 30 Hz', () => { assert.equal(MULTIPLAYER_TICK_HZ,30);assert.equal(MULTIPLAYER_TICK_DT,1/30); });
