import assert from 'node:assert/strict';
import test from 'node:test';
import { GameSimulation } from '../src/game/simulation/GameSimulation.js';
import { CommandType, fireCommand, moveCommand } from '../src/game/simulation/commands.js';
import { createSeededRng } from '../src/game/simulation/rng.js';

const create = (seed=7) => new GameSimulation({ rng: createSeededRng(seed) });
const advance = (simulation, seconds, commands=[]) => { for(let elapsed=0;elapsed<seconds;elapsed+=.02) simulation.step(.02,commands); };
const createBoundarySimulation = () => { let index=0;return new GameSimulation({rng:{next:()=>index++%2}}); };

test('initial state contains the canonical v0.5 loadout and first wave', () => { const s=create().getSnapshot();assert.equal(s.stage,1);assert.equal(s.player.hp,100);assert.equal(s.player.armor,60);assert.equal(s.player.ammo,28);assert.equal(s.player.reserveAmmo,112);assert.equal(s.player.grenades,3);assert.equal(s.enemies.length,3); });
test('move command integrates player movement', () => { const g=create(),x=g.getSnapshot().player.x;advance(g,.2,[moveCommand(1,0)]);assert.ok(g.getSnapshot().player.x>x); });
test('fire command consumes ammunition and creates a bullet', () => { const g=create();g.step(0,[fireCommand(true)]);const s=g.getSnapshot();assert.equal(s.player.ammo,27);assert.equal(s.bullets.length,1);assert.equal(g.drainEvents()[0].type,'shot-fired'); });
test('reload advances exclusively with dt and transfers reserve ammunition', () => { const g=create();g.step(0,[fireCommand(true)]);g.step(0,[fireCommand(false),{type:CommandType.RELOAD}]);assert.equal(g.getSnapshot().player.reloadTimer,.82);g.step(0,[]);assert.equal(g.getSnapshot().player.ammo,27);advance(g,.84);const s=g.getSnapshot();assert.equal(s.player.ammo,28);assert.equal(s.player.reserveAmmo,111); });
test('dash moves, starts cooldown, and blocks a repeated dash', () => { const g=create();g.step(0,[moveCommand(1,0),{type:CommandType.DASH}]);const first=g.getSnapshot();assert.ok(first.player.x>180);assert.equal(first.player.dashTimer,.15);assert.equal(first.player.dashCooldown,1.45);g.step(0,[{type:CommandType.DASH}]);assert.equal(g.getSnapshot().player.x,first.player.x);advance(g,1.5);g.step(0,[{type:CommandType.DASH}]);assert.ok(g.getSnapshot().player.dashCooldown>0); });
test('damage consumes armor before hp and supports death', () => { const g=create();g.damagePlayer(70);let s=g.getSnapshot();assert.equal(s.player.armor,0);assert.equal(s.player.hp,90);advance(g,.3);g.damagePlayer(100);s=g.getSnapshot();assert.equal(s.player.hp,0);assert.equal(s.dead,true);assert.equal(s.paused,true); });
test('enemy kills increment kills and wave two uses simulation timer', () => { const g=create();for(const e of g.getSnapshot().enemies)g.damageEnemy(e.id,1000);let s=g.getSnapshot();assert.equal(s.kills,3);assert.ok(s.waveSpawnTimer>0);assert.equal(s.enemies.length,3);advance(g,.5);s=g.getSnapshot();assert.equal(s.enemies.length,6);assert.equal(s.wave,2); });
test('stage transition initializes Warden-X with 1200 hp', () => { const g=create();g.completeStageOne();advance(g,.1);const s=g.getSnapshot();assert.equal(s.stage,2);assert.equal(s.boss.hp,1200);assert.equal(s.boss.maxHp,1200); });
test('boss phase thresholds activate only at the next attack pattern boundary', () => { const g=create();g.skipToBoss();g.damageBoss(401);assert.equal(g.getSnapshot().boss.phase,1);advance(g,.7);assert.equal(g.getSnapshot().boss.phase,1);advance(g,.2);assert.equal(g.getSnapshot().boss.phase,2);g.damageBoss(400);assert.equal(g.getSnapshot().boss.phase,2);advance(g,.5);assert.equal(g.getSnapshot().boss.phase,2);advance(g,.3);assert.equal(g.getSnapshot().boss.phase,3); });
test('boss damage reaches victory and emits boss-defeated', () => { const g=create();g.skipToBoss();g.drainEvents();g.damageBoss(1200);const s=g.getSnapshot();assert.equal(s.boss.hp,0);assert.equal(s.won,true);assert.ok(g.drainEvents().some(e=>e.type==='boss-defeated')); });
test('snapshot is copied, JSON serializable, and contains plain data', () => { const g=create(),s=g.getSnapshot();assert.doesNotThrow(()=>JSON.stringify(s));s.player.hp=1;assert.equal(g.getSnapshot().player.hp,100);const visit=value=>{assert.notEqual(typeof value,'function');if(value&&typeof value==='object'){assert.ok(Array.isArray(value)||Object.getPrototypeOf(value)===Object.prototype);Object.values(value).forEach(visit)}};visit(s); });
test('identical commands and deterministic RNG yield identical snapshots', () => { const run=()=>{const g=create(99);for(let i=0;i<150;i++)g.step(.016,[moveCommand(i<70?1:0,i>80?-1:0),fireCommand(i%20<8)]);return g.getSnapshot()};assert.deepEqual(run(),run()); });
test('restart and delayed reinforcements identify their wave in events', () => { const g=create();g.restart();assert.deepEqual(g.drainEvents(),[{type:'wave-started',wave:1}]);for(const e of g.getSnapshot().enemies)g.damageEnemy(e.id,1000);g.drainEvents();advance(g,.5);assert.ok(g.drainEvents().some(event=>event.type==='wave-started'&&event.wave===2)); });
test('danger zones retain the v0.5 phase-specific arena bounds', () => { const check=(damage,bounds,count=1)=>{const g=createBoundarySimulation();g.skipToBoss();if(damage)g.damageBoss(damage);advance(g,.82);const zones=g.getSnapshot().dangerZones;assert.equal(zones.length,count);for(const zone of zones){assert.ok(zone.x>=bounds.minX&&zone.x<=bounds.maxX);assert.ok(zone.y>=bounds.minY&&zone.y<=bounds.maxY)}};check(0,{minX:35,maxX:325,minY:280,maxY:490});check(401,{minX:32,maxX:328,minY:275,maxY:492});check(801,{minX:30,maxX:330,minY:270,maxY:494},2); });
test('boss hit flash distinguishes bullets from grenade explosions', () => { const g=create();g.skipToBoss();g.damageBoss(1);assert.equal(g.getSnapshot().boss.flashTimer,.06);g.step(0,[{type:CommandType.GRENADE}]);assert.equal(g.getSnapshot().boss.flashTimer,.12); });
